/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import DAO.EstadoDAO;
import DAO.FarmaciaDAO;
import DAO.LocalidadDAO;
import DAO.MotivoDAO;
import DAO.RegionDAO;
import VO.EstadoVO;
import VO.FarmaciaVO;
import VO.LocalidadVO;
import VO.MotivoVO;
import VO.RegionVO;
import java.time.LocalDate;
import javax.swing.JOptionPane;

/**
 *
 * @author Chant
 */
public class JBMFarmacia extends javax.swing.JFrame {

    /**
     * Creates new form JRegistrarFarmacia
     */
    public JBMFarmacia() {
        initComponents();
        int ancho = java.awt.Toolkit.getDefaultToolkit().getScreenSize().width;
        int alto = java.awt.Toolkit.getDefaultToolkit().getScreenSize().height;
        
        //utiliza un combobox para seleccionar la farmacia que se desea mostrar los datos
        FarmaciaDAO FDAO = new FarmaciaDAO();
        FDAO.Consultar_Farmacia(jComboBoxFarmacia);
        
        jTextAreaDetalleMotivo.setEditable(false);// solo se activa cuando se busca y se carga
                                                  //  en el jframe y el campo estado es true
        
        // estos campos estan desactivados porque no se pueden modificar
        jTextProvincia.setEnabled(false);
        jTextLocalidad.setEnabled(false);
        jTextCodigoPostal.setEnabled(false);
        jTextEstado.setEnabled(false);
        
        setDefaultCloseOperation(JBMFarmacia.DISPOSE_ON_CLOSE);//para salir de la ventana sin salir del programa

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButtonEliminar = new javax.swing.JButton();
        jButtonGuardar = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jTextNombre = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel5 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        jTextLocalidad = new javax.swing.JTextField();
        jTextProvincia = new javax.swing.JTextField();
        jSeparator4 = new javax.swing.JSeparator();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jTextCodigoPostal = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jTextEstado = new javax.swing.JTextField();
        jSeparator5 = new javax.swing.JSeparator();
        jTextEmail = new javax.swing.JTextField();
        jSeparator6 = new javax.swing.JSeparator();
        jTextDireccion = new javax.swing.JTextField();
        jSeparator7 = new javax.swing.JSeparator();
        jSeparator8 = new javax.swing.JSeparator();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jSeparator10 = new javax.swing.JSeparator();
        jLabel13 = new javax.swing.JLabel();
        jTextTelefono = new javax.swing.JTextField();
        jButtonBuscar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaDetalleMotivo = new javax.swing.JTextArea();
        jLabel3 = new javax.swing.JLabel();
        jComboBoxFarmacia = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(245, 245, 245));
        jPanel1.setMaximumSize(new java.awt.Dimension(500, 700));
        jPanel1.setMinimumSize(new java.awt.Dimension(250, 350));
        jPanel1.setPreferredSize(new java.awt.Dimension(500, 700));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(22, 39, 49));
        jLabel1.setFont(new java.awt.Font("Montserrat", 1, 16)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(22, 39, 49));
        jLabel1.setText("Modificar datos");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 10, -1, -1));
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 0, 40, 30));

        jButtonEliminar.setBackground(new java.awt.Color(215, 52, 56));
        jButtonEliminar.setFont(new java.awt.Font("Montserrat", 1, 14)); // NOI18N
        jButtonEliminar.setForeground(new java.awt.Color(255, 255, 255));
        jButtonEliminar.setText("Eliminar");
        jButtonEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEliminarActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 660, 160, 50));

        jButtonGuardar.setFont(new java.awt.Font("Montserrat", 1, 14)); // NOI18N
        jButtonGuardar.setForeground(new java.awt.Color(255, 255, 255));
        jButtonGuardar.setText("Guardar");
        jButtonGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGuardarActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 660, 160, 50));

        jLabel4.setFont(new java.awt.Font("Montserrat", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(22, 39, 49));
        jLabel4.setText("Nombre");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 110, -1, 20));

        jTextNombre.setFont(new java.awt.Font("Montserrat", 0, 12)); // NOI18N
        jTextNombre.setAlignmentX(0.0F);
        jTextNombre.setAlignmentY(0.0F);
        jTextNombre.setBorder(null);
        jTextNombre.setOpaque(false);
        jTextNombre.setSelectedTextColor(new java.awt.Color(0, 0, 0));
        jTextNombre.setSelectionColor(new java.awt.Color(0, 0, 0));
        jPanel1.add(jTextNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 130, 230, 30));
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 150, 250, 10));

        jLabel5.setFont(new java.awt.Font("Montserrat", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(22, 39, 49));
        jLabel5.setText("Localidad");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 230, -1, 20));
        jPanel1.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 270, 250, 10));

        jTextLocalidad.setFont(new java.awt.Font("Montserrat", 0, 12)); // NOI18N
        jTextLocalidad.setAlignmentX(0.0F);
        jTextLocalidad.setAlignmentY(0.0F);
        jTextLocalidad.setBorder(null);
        jTextLocalidad.setOpaque(false);
        jTextLocalidad.setSelectedTextColor(new java.awt.Color(0, 0, 0));
        jTextLocalidad.setSelectionColor(new java.awt.Color(0, 0, 0));
        jPanel1.add(jTextLocalidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 230, 230, 30));

        jTextProvincia.setFont(new java.awt.Font("Montserrat", 0, 12)); // NOI18N
        jTextProvincia.setAlignmentX(0.0F);
        jTextProvincia.setAlignmentY(0.0F);
        jTextProvincia.setBorder(null);
        jTextProvincia.setOpaque(false);
        jTextProvincia.setSelectedTextColor(new java.awt.Color(0, 0, 0));
        jTextProvincia.setSelectionColor(new java.awt.Color(0, 0, 0));
        jTextProvincia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextProvinciaActionPerformed(evt);
            }
        });
        jPanel1.add(jTextProvincia, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 170, 230, 30));
        jPanel1.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 210, 250, 10));

        jLabel6.setFont(new java.awt.Font("Montserrat", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(22, 39, 49));
        jLabel6.setText("Provincia");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 170, -1, 20));

        jLabel7.setFont(new java.awt.Font("Montserrat", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(22, 39, 49));
        jLabel7.setText("Código postal");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 280, -1, 20));

        jTextCodigoPostal.setFont(new java.awt.Font("Montserrat", 0, 12)); // NOI18N
        jTextCodigoPostal.setAlignmentX(0.0F);
        jTextCodigoPostal.setAlignmentY(0.0F);
        jTextCodigoPostal.setBorder(null);
        jTextCodigoPostal.setOpaque(false);
        jTextCodigoPostal.setSelectedTextColor(new java.awt.Color(0, 0, 0));
        jTextCodigoPostal.setSelectionColor(new java.awt.Color(0, 0, 0));
        jPanel1.add(jTextCodigoPostal, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 280, 230, 30));

        jLabel8.setFont(new java.awt.Font("Montserrat", 1, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(22, 39, 49));
        jLabel8.setText("Dirección");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 340, -1, 20));

        jLabel9.setFont(new java.awt.Font("Montserrat", 1, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(22, 39, 49));
        jLabel9.setText("E-Mail");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 390, -1, 20));

        jLabel10.setFont(new java.awt.Font("Montserrat", 1, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(22, 39, 49));
        jLabel10.setText("Teléfono");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 440, -1, 20));

        jTextEstado.setFont(new java.awt.Font("Montserrat", 0, 12)); // NOI18N
        jTextEstado.setAlignmentX(0.0F);
        jTextEstado.setAlignmentY(0.0F);
        jTextEstado.setBorder(null);
        jTextEstado.setOpaque(false);
        jTextEstado.setSelectedTextColor(new java.awt.Color(0, 0, 0));
        jTextEstado.setSelectionColor(new java.awt.Color(0, 0, 0));
        jTextEstado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextEstadoActionPerformed(evt);
            }
        });
        jPanel1.add(jTextEstado, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 480, 230, 30));
        jPanel1.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 460, 250, 10));

        jTextEmail.setFont(new java.awt.Font("Montserrat", 0, 12)); // NOI18N
        jTextEmail.setAlignmentX(0.0F);
        jTextEmail.setAlignmentY(0.0F);
        jTextEmail.setBorder(null);
        jTextEmail.setOpaque(false);
        jTextEmail.setSelectedTextColor(new java.awt.Color(0, 0, 0));
        jTextEmail.setSelectionColor(new java.awt.Color(0, 0, 0));
        jTextEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextEmailActionPerformed(evt);
            }
        });
        jPanel1.add(jTextEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 390, 230, 30));
        jPanel1.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 420, 250, 10));

        jTextDireccion.setFont(new java.awt.Font("Montserrat", 0, 12)); // NOI18N
        jTextDireccion.setAlignmentX(0.0F);
        jTextDireccion.setAlignmentY(0.0F);
        jTextDireccion.setBorder(null);
        jTextDireccion.setOpaque(false);
        jTextDireccion.setSelectedTextColor(new java.awt.Color(0, 0, 0));
        jTextDireccion.setSelectionColor(new java.awt.Color(0, 0, 0));
        jPanel1.add(jTextDireccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 330, 230, 30));
        jPanel1.add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 370, 250, 10));
        jPanel1.add(jSeparator8, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 320, 250, 10));

        jLabel11.setFont(new java.awt.Font("Montserrat", 1, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(22, 39, 49));
        jLabel11.setText("Buscar Farmacia: ");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 50, -1, 20));
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 110, -1, -1));
        jPanel1.add(jSeparator10, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 520, 250, 10));

        jLabel13.setFont(new java.awt.Font("Montserrat", 1, 12)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(22, 39, 49));
        jLabel13.setText("Estado");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 490, -1, 20));

        jTextTelefono.setFont(new java.awt.Font("Montserrat", 0, 12)); // NOI18N
        jTextTelefono.setAlignmentX(0.0F);
        jTextTelefono.setAlignmentY(0.0F);
        jTextTelefono.setBorder(null);
        jTextTelefono.setOpaque(false);
        jTextTelefono.setSelectedTextColor(new java.awt.Color(0, 0, 0));
        jTextTelefono.setSelectionColor(new java.awt.Color(0, 0, 0));
        jTextTelefono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextTelefonoActionPerformed(evt);
            }
        });
        jPanel1.add(jTextTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 440, 230, 30));

        jButtonBuscar.setText("Buscar");
        jButtonBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBuscarActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 90, -1, -1));

        jTextAreaDetalleMotivo.setColumns(20);
        jTextAreaDetalleMotivo.setRows(5);
        jScrollPane1.setViewportView(jTextAreaDetalleMotivo);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 560, 410, -1));

        jLabel3.setText("Detalle del Motivo de la baja");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 540, -1, -1));

        jPanel1.add(jComboBoxFarmacia, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 90, 250, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 720, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 11, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEliminarActionPerformed
        // TODO add your handling code here:
        // la eliminacion es una baja logica, es decir, solo altero el campo
        //estado y motivo (que solo se completa cuando es una baja)
        // para detallar el motivo de la baja

        FarmaciaVO FVO = new FarmaciaVO();
        FarmaciaDAO FDAO = new FarmaciaDAO();

        MotivoVO MVO = new MotivoVO();
        MotivoDAO MDAO = new MotivoDAO();

        if (jTextEstado.getText().equals("true")) { //corrobora que el campo estado de la farmacia se activo
            //guarda primero el motivo en la tabla motivo
            
            MVO.setMotivo(jTextAreaDetalleMotivo.getText());
            MDAO.Agregar_MotivoVO(MVO);
            //luego modifica los campos estado y motivo(teniendo en cuenta el id del ultimo
            //motivo generado en la tabla motivo)
            FVO.setId_Farmacia(jComboBoxFarmacia.getSelectedIndex());
            FVO.setId_Motivo(MDAO.id_M);//id_M es una variable global que toma el valor
            FVO.setId_Estado(1);        //del ultimo id generado en la tabla motivo
            FDAO.Eliminar_FarmaciaVO(FVO);//que sirve para vincular la farmacia con el motivo de la baja

        } else{
            JOptionPane.showMessageDialog(null, "La farmacia se encuentra momentaneamente fuera de servio", "Información", JOptionPane.INFORMATION_MESSAGE);
        }

    }//GEN-LAST:event_jButtonEliminarActionPerformed

    private void jButtonGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGuardarActionPerformed
        // TODO add your handling code here:
        //Guarda los datos de la farmacia solo el nombre, direccion, email, telefono solamente
        FarmaciaVO FVO = new FarmaciaVO();
        FarmaciaDAO FDAO = new FarmaciaDAO();

        //toma los datos de los jtext y los coloca en la instancia de farmacia
        FVO.setId_Farmacia(jComboBoxFarmacia.getSelectedIndex());
        FVO.setNombre(jTextNombre.getText());
        FVO.setDireccion(jTextDireccion.getText());
        FVO.setEMail(jTextEmail.getText());
        FVO.setTelefono(Integer.parseInt(jTextTelefono.getText()));

        //llama a la funcion que permite modificar los datos de la farmacia
        FDAO.Modificar_FarmaciaVO(FVO);
    }//GEN-LAST:event_jButtonGuardarActionPerformed

    private void jTextProvinciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextProvinciaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextProvinciaActionPerformed

    private void jTextEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextEmailActionPerformed

    private void jTextEstadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextEstadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextEstadoActionPerformed

    private void jTextTelefonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextTelefonoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextTelefonoActionPerformed

    private void jButtonBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBuscarActionPerformed
        // TODO add your handling code here:
        //este metodo realiza la busqueda por el Id de la farmacia;
        //pero emplea el combobox para seleccionar la farmacia que desea buscar 
        // y luego toma el indice del combobox (que es igual al id de la tabla datos_farmacia)
        //y lo utiliza para realzar la busqueda en farmacias por el id.
        Integer id_f = jComboBoxFarmacia.getSelectedIndex();
        
        
        //Integer id_f = Integer.valueOf(jTextBuscarFarmacia.getText());
        Integer id_l;
        Integer id_m;
        Integer id_e;
        Integer id_r;

        FarmaciaVO FVO = new FarmaciaVO();
        FarmaciaDAO FDAO = new FarmaciaDAO();

        EstadoVO EVO = new EstadoVO();
        EstadoDAO EDAO = new EstadoDAO();

        LocalidadVO LVO = new LocalidadVO();
        LocalidadDAO LDAO = new LocalidadDAO();

        RegionVO RVO = new RegionVO();
        RegionDAO RDAO = new RegionDAO();

        FVO = FDAO.Buscar_FarmaciaVO(id_f); // busca la farmacia y se obtengo los Id de los campos
        id_l = FVO.getId_Localidad();        //localidad, motivos y estado para vincular a esas tablas
        id_m = FVO.getId_Motivo();
        id_e = FVO.getId_Estado();

        LVO = LDAO.Buscar_LocalidadVO(id_l); //con el id de la localidad obtengo el id de la region 
        id_r = LVO.getId_Region();        // para obtener los campos de lcoalidad y vincular a la tabla region

        RVO = RDAO.Buscar_RegionVO(id_r);    // Busca la region por id de region obtenido

        EVO = EDAO.Buscar_EstadoVO(id_e);   // Busca el motivo por el id del motivo

        //muestra los campos de la farmacia que se obtuvieron de todas las tablas en 
        //los jtext del jframe
        jTextNombre.setText(FVO.getNombre());
        jTextProvincia.setText(RVO.getNombre());
        jTextDireccion.setText(FVO.getDireccion());
        jTextEmail.setText(FVO.getEMail());
        jTextTelefono.setText(Integer.toString(FVO.getTelefono()));
        jTextLocalidad.setText(LVO.getNombre());
        jTextCodigoPostal.setText(LVO.getCodp());
        jTextEstado.setText(Boolean.toString(EVO.isEstado()));
        
        //se utiliza para habilitar el area de texto que detalla el motivo de la baja
        //solo si el campo estado es activo, es decir, true.
        //recordando que solo se completa el campo motivo cuando se da de baja una farmacia
        if(jTextEstado.getText().equals("true")){
        jTextAreaDetalleMotivo.setEditable(true);
        }
    }//GEN-LAST:event_jButtonBuscarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonBuscar;
    private javax.swing.JButton jButtonEliminar;
    private javax.swing.JButton jButtonGuardar;
    private javax.swing.JComboBox<String> jComboBoxFarmacia;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator10;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JTextArea jTextAreaDetalleMotivo;
    private javax.swing.JTextField jTextCodigoPostal;
    private javax.swing.JTextField jTextDireccion;
    private javax.swing.JTextField jTextEmail;
    private javax.swing.JTextField jTextEstado;
    private javax.swing.JTextField jTextLocalidad;
    private javax.swing.JTextField jTextNombre;
    private javax.swing.JTextField jTextProvincia;
    private javax.swing.JTextField jTextTelefono;
    // End of variables declaration//GEN-END:variables
}
