/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import DAO.LaboratorioDAO;
import DAO.MedicamentosDAO;
import VO.LaboratorioVO;
import VO.MedicamentosVO;

/**
 *
 * @author Chant
 */
public class JRegistrarMedicamentos extends javax.swing.JFrame {

    /**
     * Creates new form JRegistrarFarmacia
     */
    public JRegistrarMedicamentos() {
        initComponents();
        int ancho = java.awt.Toolkit.getDefaultToolkit().getScreenSize().width;
        int alto = java.awt.Toolkit.getDefaultToolkit().getScreenSize().height;
        
        //utiliza un combobox para seleccionar la farmacia que se desea mostrar los datos
        LaboratorioDAO LDAO = new LaboratorioDAO();
        LDAO.Consultar_Laboratorio(jComboBoxLaboratorio);
               
        setDefaultCloseOperation(JBMLaboratorio.DISPOSE_ON_CLOSE);//para salir de la ventana sin salir del programa
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jSeparator9 = new javax.swing.JSeparator();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextFieldNombreMedicamento = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel5 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        jTextFieldPrecio = new javax.swing.JTextField();
        jTextFieldDetalleMedicamento = new javax.swing.JTextField();
        jSeparator4 = new javax.swing.JSeparator();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jTextFieldUnidades = new javax.swing.JTextField();
        jSeparator5 = new javax.swing.JSeparator();
        jLabel8 = new javax.swing.JLabel();
        jSeparator6 = new javax.swing.JSeparator();
        jSeparator7 = new javax.swing.JSeparator();
        jLabel9 = new javax.swing.JLabel();
        jSeparator8 = new javax.swing.JSeparator();
        jLabel10 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jSeparator10 = new javax.swing.JSeparator();
        jTextFieldNombreLaboratorio = new javax.swing.JTextField();
        jTextFieldDireccion = new javax.swing.JTextField();
        jTextFieldE_Mail = new javax.swing.JTextField();
        jTextFieldTelefono = new javax.swing.JTextField();
        jButtonGuardar = new javax.swing.JButton();
        jButtonCargarDatos = new javax.swing.JButton();
        jComboBoxLaboratorio = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(245, 245, 245));
        jPanel1.setMaximumSize(new java.awt.Dimension(500, 700));
        jPanel1.setMinimumSize(new java.awt.Dimension(250, 350));
        jPanel1.setPreferredSize(new java.awt.Dimension(500, 700));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(22, 39, 49));
        jLabel1.setFont(new java.awt.Font("Montserrat", 1, 16)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(22, 39, 49));
        jLabel1.setText("Registrar Medicamento");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 20, -1, -1));
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 20, 30, 20));
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 80, -1, -1));

        jLabel11.setFont(new java.awt.Font("Montserrat", 1, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(22, 39, 49));
        jLabel11.setText("Ingrese ID de Laboratorio: ");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 50, -1, 20));
        jPanel1.add(jSeparator9, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 100, 250, 10));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Montserrat", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(22, 39, 49));
        jLabel3.setText("Datos Medicamentos");
        jLabel3.setAlignmentY(0.0F);
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 10, -1, -1));

        jLabel4.setFont(new java.awt.Font("Montserrat", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(22, 39, 49));
        jLabel4.setText("Nombre");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 40, -1, 20));

        jTextFieldNombreMedicamento.setFont(new java.awt.Font("Montserrat", 0, 12)); // NOI18N
        jTextFieldNombreMedicamento.setAlignmentX(0.0F);
        jTextFieldNombreMedicamento.setAlignmentY(0.0F);
        jTextFieldNombreMedicamento.setBorder(null);
        jTextFieldNombreMedicamento.setOpaque(false);
        jTextFieldNombreMedicamento.setSelectedTextColor(new java.awt.Color(0, 0, 0));
        jTextFieldNombreMedicamento.setSelectionColor(new java.awt.Color(0, 0, 0));
        jPanel2.add(jTextFieldNombreMedicamento, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 50, 230, 30));
        jPanel2.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 80, 250, 10));

        jLabel5.setFont(new java.awt.Font("Montserrat", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(22, 39, 49));
        jLabel5.setText("Detalle");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 90, -1, 20));
        jPanel2.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 180, 90, 10));

        jTextFieldPrecio.setFont(new java.awt.Font("Montserrat", 0, 12)); // NOI18N
        jTextFieldPrecio.setAlignmentX(0.0F);
        jTextFieldPrecio.setAlignmentY(0.0F);
        jTextFieldPrecio.setBorder(null);
        jTextFieldPrecio.setOpaque(false);
        jTextFieldPrecio.setSelectedTextColor(new java.awt.Color(0, 0, 0));
        jTextFieldPrecio.setSelectionColor(new java.awt.Color(0, 0, 0));
        jPanel2.add(jTextFieldPrecio, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 150, 70, 30));

        jTextFieldDetalleMedicamento.setFont(new java.awt.Font("Montserrat", 0, 12)); // NOI18N
        jTextFieldDetalleMedicamento.setAlignmentX(0.0F);
        jTextFieldDetalleMedicamento.setAlignmentY(0.0F);
        jTextFieldDetalleMedicamento.setBorder(null);
        jTextFieldDetalleMedicamento.setOpaque(false);
        jTextFieldDetalleMedicamento.setSelectedTextColor(new java.awt.Color(0, 0, 0));
        jTextFieldDetalleMedicamento.setSelectionColor(new java.awt.Color(0, 0, 0));
        jPanel2.add(jTextFieldDetalleMedicamento, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 110, 230, 30));
        jPanel2.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 130, 250, 10));

        jLabel6.setFont(new java.awt.Font("Montserrat", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(22, 39, 49));
        jLabel6.setText("Precio");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 140, -1, 20));

        jLabel7.setFont(new java.awt.Font("Montserrat", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(22, 39, 49));
        jLabel7.setText("Unidades");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 140, -1, 20));

        jTextFieldUnidades.setFont(new java.awt.Font("Montserrat", 0, 12)); // NOI18N
        jTextFieldUnidades.setAlignmentX(0.0F);
        jTextFieldUnidades.setAlignmentY(0.0F);
        jTextFieldUnidades.setBorder(null);
        jTextFieldUnidades.setOpaque(false);
        jTextFieldUnidades.setSelectedTextColor(new java.awt.Color(0, 0, 0));
        jTextFieldUnidades.setSelectionColor(new java.awt.Color(0, 0, 0));
        jPanel2.add(jTextFieldUnidades, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 150, 70, 30));
        jPanel2.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 180, 90, 10));

        jLabel8.setFont(new java.awt.Font("Montserrat", 1, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(22, 39, 49));
        jLabel8.setText("Nombre Laboratorio");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 190, -1, 20));
        jPanel2.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 280, 250, 10));
        jPanel2.add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 330, 250, 10));

        jLabel9.setFont(new java.awt.Font("Montserrat", 1, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(22, 39, 49));
        jLabel9.setText("Dirección");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 240, -1, 20));
        jPanel2.add(jSeparator8, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 230, 250, 10));

        jLabel10.setFont(new java.awt.Font("Montserrat", 1, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(22, 39, 49));
        jLabel10.setText("Teléfono");
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 340, -1, 20));

        jLabel13.setFont(new java.awt.Font("Montserrat", 1, 12)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(22, 39, 49));
        jLabel13.setText("E-Mail");
        jPanel2.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 290, -1, 20));
        jPanel2.add(jSeparator10, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 380, 250, 10));
        jPanel2.add(jTextFieldNombreLaboratorio, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 210, 220, -1));
        jPanel2.add(jTextFieldDireccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 250, 220, -1));
        jPanel2.add(jTextFieldE_Mail, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 300, 220, -1));
        jPanel2.add(jTextFieldTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 350, 220, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, 460, 450));

        jButtonGuardar.setFont(new java.awt.Font("Montserrat", 1, 14)); // NOI18N
        jButtonGuardar.setText("Guardar");
        jButtonGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGuardarActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 620, 160, 50));

        jButtonCargarDatos.setText("Cargar Datos");
        jButtonCargarDatos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCargarDatosActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonCargarDatos, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 70, -1, -1));

        jPanel1.add(jComboBoxLaboratorio, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 70, 230, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGuardarActionPerformed
        // TODO add your handling code here:
        MedicamentosVO MedVO = new MedicamentosVO();
        MedicamentosDAO MedDAO = new MedicamentosDAO();
        
        MedVO.setNombre(jTextFieldNombreMedicamento.getText());
        MedVO.setDetalle(jTextFieldDetalleMedicamento.getText());
        MedVO.setPrecio(Float.parseFloat(jTextFieldPrecio.getText()));
        MedVO.setUnidades_Disponibles(Integer.parseInt(jTextFieldUnidades.getText()));
        MedVO.setId_Laboratorio(jComboBoxLaboratorio.getSelectedIndex());
        MedVO.setId_Estado(2);
        
        MedDAO.AgregarMedicamento(MedVO);
        
    }//GEN-LAST:event_jButtonGuardarActionPerformed

    private void jButtonCargarDatosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCargarDatosActionPerformed
        // TODO add your handling code here:
        //Guarda los datos de la farmacia solo el nombre, direccion, email, telefono solamente
        LaboratorioVO LabVO = new LaboratorioVO();
        LaboratorioDAO LabDAO = new LaboratorioDAO();
        
       
        LabVO = LabDAO.Buscar_LaboratorioVO(jComboBoxLaboratorio.getSelectedIndex());
        jTextFieldNombreLaboratorio.setText(LabVO.getNombre());
        jTextFieldDireccion.setText(LabVO.getDireccion());
        jTextFieldE_Mail.setText(LabVO.getE_mail());
        jTextFieldTelefono.setText(Integer.toString(LabVO.getTelefono()));
    }//GEN-LAST:event_jButtonCargarDatosActionPerformed



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCargarDatos;
    private javax.swing.JButton jButtonGuardar;
    private javax.swing.JComboBox<String> jComboBoxLaboratorio;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator10;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JSeparator jSeparator9;
    private javax.swing.JTextField jTextFieldDetalleMedicamento;
    private javax.swing.JTextField jTextFieldDireccion;
    private javax.swing.JTextField jTextFieldE_Mail;
    private javax.swing.JTextField jTextFieldNombreLaboratorio;
    private javax.swing.JTextField jTextFieldNombreMedicamento;
    private javax.swing.JTextField jTextFieldPrecio;
    private javax.swing.JTextField jTextFieldTelefono;
    private javax.swing.JTextField jTextFieldUnidades;
    // End of variables declaration//GEN-END:variables
}
